//
module.exports = function (sequelize, DataTypes) {

    var User = sequelize.define("User", {
        firstName: {
            type: DataTypes.STRING,
            allowNull: false,
             // don't add the timestamp attributes (updatedAt, createdAt) to the table
            timestamps: false,
        },
        lastName: {
            type: DataTypes.STRING,
            allowNull: false,
            timestamps: false,
        },
        email: {
            type: DataTypes.STRING,
            allowNull: false,
            timestamps: false,
        },
        mobile: {
            type: DataTypes.BIGINT,
            allowNull: false,
            timestamps: false,
        },
        address: {
            type: DataTypes.STRING,
            allowNull: false,
            timestamps: false,
        },
        zipcode: {
            type: DataTypes.INTEGER,
            allowNull: false,
            timestamps: false,
        },
        // this image data is post routed to cloudinary & url is generated by cloudinary then posted to mysql
        userImageURL: {
            type: DataTypes.STRING,
            allowNull: true,
            timestamps: false,
        }

    });

    User.associate = function (models) {
        User.hasMany(models.Review, {
            onDelete: "cascade"
        })
    }

    return User;
};